# Generated by Django 3.2.2 on 2021-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=1)),
                ('priimek', models.CharField(max_length=1)),
                ('emso', models.BigIntegerField()),
                ('mail', models.EmailField(max_length=60)),
                ('datum_vpisa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
