# Generated by Django 3.2.2 on 2021-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='emso',
            field=models.BigIntegerField(unique=True),
        ),
    ]
