# Generated by Django 3.2.2 on 2021-05-19 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0002_alter_prijava_emso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='emso',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('emso_oblika')]),
        ),
    ]
