# Generated by Django 3.2.2 on 2021-05-19 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0005_alter_prijava_emso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='emso',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('[0-3][0-9][0,1][0-9][0-9][0-9][0-9][5][0][5,0][0-9][0-9][0-9]')]),
        ),
    ]
