# Generated by Django 3.2.2 on 2021-05-19 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0007_alter_prijava_emso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='emso',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('[0,1,2,3]\\d[0,1]\\d{4}50[0,5]\\d{3}')]),
        ),
    ]
