# Generated by Django 3.2.2 on 2021-05-19 19:36

from django.db import migrations, models
import prijava.models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0008_alter_prijava_emso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='ime',
            field=models.CharField(max_length=1, validators=[prijava.models.is_letter]),
        ),
        migrations.AlterField(
            model_name='prijava',
            name='priimek',
            field=models.CharField(max_length=1, validators=[prijava.models.is_letter]),
        ),
    ]
