# Generated by Django 3.2.2 on 2021-05-19 20:42

from django.db import migrations, models
import prijava.models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0009_auto_20210519_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='emso',
            field=models.BigIntegerField(unique=True, validators=[prijava.models.emso_regex]),
        ),
    ]
