# Generated by Django 3.2.2 on 2021-05-20 13:45

from django.db import migrations, models
import prijava.models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0010_alter_prijava_emso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='emso',
            field=models.CharField(max_length=13, unique=True, validators=[prijava.models.emso_regex, prijava.models.emso_verify]),
        ),
    ]
